### ISSUE TITLE
Model field name clash in django 1.9

### ISSUE THREAD

**Issue by jproffitt** [divio/djangocms-file#16]
Now that CMS 3.2.1 supports django 1.9, I gave it a try. Unfortunately, this plugin will not work.

The error I am getting is:

    ERRORS:
    djangocms_file.File.file: (models.E006) The field 'file' clashes with the field 'file' from model 'cms.cmsplugin'.

This happens because `djangocms_file.File` inherits from `CMSPlugin`. So then `CMSPlugin` will have an implicit `OneToOneField ` back to `djangocms_file.File`, and it will be the lowercased version of the `File` class. (`file`) Then, the `File` class contains a `file` field of itself. So it is basically clashing with itself.

I am not sure why this didn't break before django 1.9. I'm guessing django used to not check for that?

Django CMS's docs even warn about doing this at http://docs.django-cms.org/en/develop/how_to/custom_plugins.html#storing-configuration:

> You cannot name your model fields the same as any installed plugins lower- cased model name, due to the implicit one-to-one relation Django uses for sub-classed models.

**Comment by jproffitt** [comment]
I can think of 3 ways to fix this.

1. According to https://docs.djangoproject.com/en/1.9/ref/models/fields/#django.db.models.OneToOneField.parent_link, I believe you can manually set up the parent one-to-one relationship, then you could change the reverse field name. Something like this on `File`:

    parent = modes.OneToOneField(parent_link=True, related_name='file_model`)

2. Change the model name from `File` to something else`
3. Change the `File.file` field name to something else.

I think either of these fixes would introduce a migration. But I'm not sure which one would provide the best backwards-comparability. I would think option 1 would not really affect much. I'm not sure what options 2 and 3 would affect.

Let me know what you think the best option is, and I'll be happy to provide a PR for it.

**Comment by thanosd** [comment]
It looks like this is already fixed (https://github.com/divio/djangocms-file/pull/13).

Can we bump the version and make a release?

**Comment by saeedsq** [comment]
I'm experiencing the same error:

    djangocms_file.File.file: (models.E006) The field 'file' clashes with the field 'file' from model 'cms.cmsplugin'.

I'm also waiting for new release in order to use django-cms with django 1.9

**Comment by czpython** [comment]
Fixed by https://github.com/divio/djangocms-file/pull/13

**Comment by Ekbal41** [comment]
i cant find fix of this without making abstract >😔
