### ISSUE TITLE
Selecting a file opens the change form

### ISSUE THREAD

**Issue by marksweb** [divio/djangocms-file#29]
I'm just looking at integrating the file plugin, but I'm having an issue with filer opening the change form for a file instead of selecting the file to use.

Comparing what I've got with the CMS demo, the 'choose file' window for me is a full filer admin view, but on the demo it's more of a filer specific thing. 

![screen shot 2017-12-22 at 15 30 53 2](https://user-images.githubusercontent.com/1461191/34303810-007454d2-e72f-11e7-8715-84c97d1519ba.png)

I don't think there are any template overrides or anything like that, so any ideas what's causing this?

```bash
Django==1.10.8
django-cms==3.4.5
djangocms-file==2.0.2
```

**Comment by FinalAngel** [comment]
Please upgrade to Django 1.11 as Filer does not support <= 1.11 anymore. This is most likely related to filer.
