### ISSUE TITLE
wrong box sizing

### ISSUE THREAD

**Issue by zypro** [divio/djangocms-file#46]
Is this a bug since django==2.2 and djangocms==3.7.1 ?

![Bildschirmfoto 2020-03-25 um 11 46 14](https://user-images.githubusercontent.com/3543363/77529292-9f499600-6e8f-11ea-80b0-28b94baea081.png)

**Comment by FinalAngel** [comment]
@zypro I tested using:

``django==2.2`` and ``djangocms==3.7.1`` and it works as expected. Did you also install djangocms-admin-style?

**Comment by zypro** [comment]
sorry. It was a custom style which caused this issue....

**Comment by FinalAngel** [comment]
No problem @zypro, thanks for the feedback!
