### ISSUE TITLE
Upgrading from version 0.0.1 

### ISSUE THREAD

**Issue by asa511** [divio/djangocms-file#6]
Can you provide directions on how to migrate from 0.0.1 version of the plugin with lots of data to 0.1? 

Django has been upgraded to 1.7 from 1.6, south is commented out and entry also added to MIGRATION_MODULES.  Django CMS version is 3.0.12

makemigrations returns with the message "No changes detected in app 'djangocms_file'"

**Comment by mkoistinen** [comment]
Closed by #11.
